### PR TITLE
Maintenance: Tidy up server lifecycle

### PR DESCRIPTION
**Pull request by ahmedneilhussain**
Further tweaks to server lifecycle code to make it a little simpler to follow.

Avoid mutating initializeFuture from within blocks chained onto initializeFuture itself. There is no need to e.g. call initializeFuture.completeExceptionally from within an exceptionallyBlock chained onto initializeFuture! If that block is hit the future is already in a 'completed, exceptionally' state.

### CODE REVIEW

**Comment by ahmedneilhussain** [comment]
@rubenporras @mickaelistria any general thoughts? Need to be very careful making changes to this logic, so I definitely don't think we should be in a hurry to merge any of this. On the other hand, the existing code has evolved quite a lot to the point where it is very hard to reason about the lifecycle, so I think sooner or later it would be good to bite the bullet and try and rationalise things.

Would appreciate thoughts on this as a general approach.

**Comment by ahmedneilhussain** [comment]
Just fixed an issue with workspace folders. Of interest because it is related to the discussion about lifecycle and `LanguageServerWrapper` reuse (or not) in https://github.com/eclipse/lsp4e/issues/512

Two observations come to mind: we seem to be interpreting the 'workspace folders' capability slightly differently to the spec. AIUI, workspace folders are supported at basic level either as a yes or a no, and that doesn't change dynamically. The feature that can be added dynamically is subscription to the `workspaceFolders/didChange` event. That's not the same thing as pure `workspaceFolders` support - the latter is just the server's ability to send a request to the client asking for a list of workspace folders.

Secondly - what are we gaining from keeping wrappers around when the server is shut down?

**Comment by mickaelistria** [comment]
> we seem to be interpreting the 'workspace folders' capability slightly differently to the spec.

Can you please open a dedicated issue for that?

> Secondly - what are we gaining from keeping wrappers around when the server is shut down?

In case a LS instance or connection dies, then the wrapper is still supposed to be partly usable and to revive the LS. Usually, the LS keeps the same capabilities and so on, so we can keep using the wrapper to select the language servers that we will query for an operation or another even if this LS has died in the meantime.

**Comment by mickaelistria** [comment]
The initial target branch `master` was deleted and replaced by `main`, so this PR got closed automatically. If this is still relevant, please re-create this PR targetting the `main` branch.

**Pull request closed without merging**
