### PR TITLE
Get tabWidth / insertSpaces from editor preferences store

### LINKED ISSUE #245: Read from the editor preference store, not the global preference store, to retrieve formatting settings
See the discussion going on at https://github.com/eclipse/wildwebdeveloper/issues/474, from https://github.com/eclipse/wildwebdeveloper/issues/474#issuecomment-1247735627 onwards

Currently LSP4E seems to read formatting settings like 'insert tabs for spaces' from the global preference store. Projects like https://github.com/angelozerr/ec4e however allow customizing such settings on a project by project basis and offers more settings, like `trim_trailing_whitespace` and `insert_final_newline`. 

It would make the dev experience so much better if the settings from .editorconfig, applied to the editor preference store by ec4e, would get picked up by LSP4E for the  [FormattingOptions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#formattingOptions) for documentFormatting, rangeFormatting and onTypeFormatting commands

### PR DESCRIPTION
**Pull request by angelozerr**
Get tabWidth / insertSpaces from editor preferences store

Fixes #245

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
This PR provides the capability to get the `tabWidth / insertSpaces` from the editor preference store and if it find nothing, it use the global settings from Eclipse IDE.

It will give the capability to customize the insert spaces / tabs with UI preferences and .editorconfig, but it requires some changes on Platform Text I created a draft PR for that https://github.com/eclipse-platform/eclipse.platform.text/pull/109

**Review by rubenporras — APPROVED** [review]

**Review by rubenporras — CHANGES_REQUESTED** [review]
The code looks good, but some test do not compile any more. Could you take a look at those?

**Comment by angelozerr** [comment]
> The code looks good, but some test do not compile any more. Could you take a look at those?

It should work now (CI build has successed)

**Comment by rubenporras** [comment]
Agree, let us Mickael decide. Thanks for the clarification.

**Comment by sebthom** [comment]
@angelozerr is this PR still something you are working on or shall we close it?

**Comment by angelozerr** [comment]
Im sorry I have no time to work on it. You can close it if you wish.

**Pull request closed without merging**
