### PR TITLE
Indicate when content assist proposals are incomplete.

### PR DESCRIPTION
**Pull request by andrewL-avlq**
Add a place-holder proposal that indicates when the list of content assist proposals is incomplete.

### CODE REVIEW

**Comment by mickaelistria** [comment]
Can you please share a screenshot of how this looks like?

**Comment by mickaelistria** [comment]
OK. What about have the item directly saying "Continue typing for more proposals..."? Also, can we find an interesting emoji to add here in order to showcase this is not a regular entry? Something like ➕ ?

**Comment by andrewL-avlq** [comment]
No problem changing the item text. Do you want to leave the additional info as is?

**Comment by mickaelistria** [comment]
> No problem changing the item text. Do you want to leave the additional info as is?

Yes, i think we can keep it, and improve it later.

**Comment by andrewL-avlq** [comment]
Using existing icons from the Eclipse platform could look something like one of these:
2024_01_31_00_40_49_Greenshot

Or if the license allows, we could use something from https://www.iconfinder.com/search?q=more&price=free&license=gte__2 or something like https://www.iconfinder.com/icons/326714/pencil_translate_write_icon

Do any of these appeal (I quite like the pencil icon)? Or do you have a preferred site to get icons from?

**Comment by mickaelistria** [comment]
I personally like more emojis than Eclipse icons nowadays because they're consistent with my OS, are zoomable, are screen-readable...  So I would just add an emoji to the label.
Using Eclipse icons makes sense too, although it doesn't have most of the benefits mentioned above.
Using external icons would require some IP effort and would bring more visual inconsistency with OS and Eclipse workbench, I think we should avoid that.

Overall, I think either emoji or Eclipse icons are fine. Your call ;)

**Pull request merged**
