### PR TITLE
Minor code improvements

### PR DESCRIPTION
**Pull request by sebthom**

### CODE REVIEW

**Comment by mickaelistria** [comment]
Thank you!

**Comment by rubenporras** [comment]
out of curiosity, do we have a coding convention when to use var/final?

**Comment by sebthom** [comment]
I am not aware of any. I am currently using the var keyword only when an object is instantiated using the new keyword so it is immediately visible what type the variable has.

**Comment by mickaelistria** [comment]
No, there is no coding convention as long as code is readable.

**Pull request merged**
