### PR TITLE
fix mylyn URI

### PR DESCRIPTION
**Pull request by rubenporras**
The 3.0.42 is no longer available

### CODE REVIEW

**Comment by sebthom** [comment]
How about we point it to the latest 3.x release which is accessible via https://download.eclipse.org/mylyn/docs/releases/3.0/

**Comment by mickaelistria** [comment]
+1 for using latest release as much as possible.

**Comment by rubenporras** [comment]
I prefer personally fixed versions but pointing to the latest release is also fine for me.

**Comment by mickaelistria** [comment]
> I prefer personally fixed versions but pointing to the latest release is also fine for me.

I think it depends on your goal: for the *project*, it's often -if not always- better to use latest version of dependencies, unless those are known to have bugs. This improves the consuming project that usually benefits from fixes and other improvements for free, but also allows to build against some maintained version of its dependency (usually only latest release for OSS projects) so getting support is easier, and this also improves collaboration between projects and a better distribution of quality/value/activity/... across projects and thus reducing the risk illustrated in https://xkcd.com/2347/ .
For a *product* where some quality gates, manual testing, commercial commitments... are at play, then fixed versions give more certainty and reduces risk for this particular product in this particular version; so it can make more sense.

**Pull request merged**
