### PR TITLE
Fix workspace warnings

### PR DESCRIPTION
**Pull request by rubenporras**

### CODE REVIEW

**Comment by sebthom** [comment]
Do you think you could you rebase your branch instead of adding a merge commit?

**Comment by rubenporras** [comment]
Hi @sebthom , is it good now?

**Comment by sebthom** [comment]
I'm not sure, but I think the first commit should not appear in the list.

**Comment by rubenporras** [comment]
Now it should be good.

**Comment by sebthom** [comment]
Thanks!!

**Pull request merged**
