### PR TITLE
Fix selective formatting (issue #1127)

### PR DESCRIPTION
**Pull request by travkin79**
This PR fixes selective formatting.

### CODE REVIEW

**Comment by travkin79** [comment]
I think, my fix is ready, but I'd like to add an automated test for that case, too.

**Comment by rubenporras** [comment]
Thanks for the fix. It looks good to me but I will wait for the test case before merging.

**Comment by travkin79** [comment]
I think, now, the PR is ready to be merged. But please take a look at the following line. Is that the right thing to be returned in this case?

https://github.com/travkin79/lsp4e/blob/15350a9bff093771bc306cf06ffea2f25d9106c7/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/format/LSPFormatter.java#L66

**Comment by travkin79** [comment]
Hi @rubenporras,
Since this bugfix is important and urgent for my team, when do you plan to make the next LSP4E release?

**Comment by rubenporras** [comment]
> I think, now, the PR is ready to be merged. But please take a look at the following line. Is that the right thing to be returned in this case?
> 
> https://github.com/travkin79/lsp4e/blob/15350a9bff093771bc306cf06ffea2f25d9106c7/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/format/LSPFormatter.java#L66

I am also not sure and you implementation seems sensible.

In any case, I think that if the client pays attention to the capabilities of the client, we should never reach this code.

**Comment by rubenporras** [comment]
> Hi @rubenporras, Since this bugfix is important and urgent for my team, when do you plan to make the next LSP4E release?

In that case, I will prepare a new release today or tomorrow.

**Comment by rubenporras** [comment]
Hi @travkin79 ,

you have a new release ;)

Cheers.

**Comment by travkin79** [comment]
> you have a new release ;)
Hi @rubenporras,
That's awesome! Thank you very much. :-)

**Pull request merged**
