### PR TITLE
API: Enhancement to support async completion on the UI thread

### PR DESCRIPTION
**Pull request by ahmedneilhussain**
Should make for cleaner code where the follow up to a LS call needs to run on the UI thread anyway

### CODE REVIEW

**Comment by ahmedneilhussain** [comment]
@mickaelistria @rubenporras (and others) what do you think?

As you know, the new API already makes sure any publicly returned CompletableFuture completes on a background thread to make sure the users can't schedule arbitrary follow-up work and tie up the LS inbound listener thread - that's what all those `.thenApplyAsync(Function.identity())` calls are doing.

I realised it was a simple enhancement to optionally deliver the results on the UI thread rather than an arbitrary pool thread. In many cases this is how the results are going to get used anyway, so this gets rid of a layer of nested lambda functions.

**Comment by mickaelistria** [comment]
I don't think it's necessary to have new API for that. Since Display implements Executor, one can now do `future.thenAcceptAsync(result -> widget.setText(result), widget.getDisplay())` to run code in UI Thread. One new construct is IMO not better than finding way to encourage consumers to use a more standard pattern.

The typical pattern would be
```java
LanguageServers.collectAll(ls -> ls.getCompletion()) // get LS info
  .thenApplyAsync(lsCompletions -> lsCompletions.stream().map(lsCompletion -> toEclipseCompletion(lsCompletion))) // map it to Eclipse domain in another thread
  .thenAcceptAsync(eclipseCompletions -> showInUI(eclipseCompletions), display);
```
So one should rarely go straight from LS to UI Thread because data transformation should not require/block one nor the other; thus I don't think the proposed API is so helpful.

**Comment by ahmedneilhussain** [comment]
Ha! I hadn't realised `Display` implements `Executor` - you're quite right, that works out of the box, so this change is unnecessary.

Cheers.

**Comment by mickaelistria** [comment]
> Ha! I hadn't realised Display implements Executor

It's pretty recent; an great idea and implementation from @laeubi

**Comment by ahmedneilhussain** [comment]
> I don't think it's necessary to have new API for that. Since Display implements Executor, one can now do `future.thenAcceptAsync(result -> widget.setText(result), widget.getDisplay())` to run code in UI Thread. One new construct is IMO not better than finding way to encourage consumers to use a more standard pattern.
> 
> The typical pattern would be
> 
> ```java
> LanguageServers.collectAll(ls -> ls.getCompletion()) // get LS info
>   .thenApplyAsync(lsCompletions -> lsCompletions.stream().map(lsCompletion -> toEclipseCompletion(lsCompletion))) // map it to Eclipse domain in another thread
>   .thenAcceptAsync(eclipseCompletions -> showInUI(eclipseCompletions), display);
> ```
> 
> So one should rarely go straight from LS to UI Thread because data transformation should not require/block one nor the other; thus I don't think the proposed API is so helpful.

By the way, the first `.thenApplyAsync(lsCompletions -> etc. etc.` doesn't need the `async` - it's already in another thread by virtue of that `.thenApplyAsync(Function.identity())` in `LanguageServers`

**Comment by mickaelistria** [comment]
> By the way, the first .thenApplyAsync(lsCompletions -> etc. etc. doesn't need the async - it's already in another thread by virtue of that .thenApplyAsync(Function.identity()) in LanguageServers

Right, and that's great because it's extremely easy to miss the Async suffix. Just by writing this example, I had already missed it ;)

**Comment by laeubi** [comment]
> So one should rarely go straight from LS to UI Thread because data transformation should not require/block one nor the other; thus I don't think the proposed API is so helpful.

Just in case you want visual feedback there is now also `BusyIndicator#compute` and `BusyIndicator#execute`

**Pull request closed without merging**
