### PR TITLE
Undo operation fails to correctly restore text #178

### PR DESCRIPTION
**Pull request by vrubezhny**
Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>

### CODE REVIEW

**Comment by vrubezhny** [comment]
@mickaelistria So, finally the test works, but unfortunately it succeeds, so it doesn't catch the issue

**Comment by mickaelistria** [comment]
> so it doesn't catch the issue:

Can you reproduce the issue with the Mock Language Server manually? With Run As > Eclipse Application on the test fragment, and running the steps automated in this test?

**Comment by vrubezhny** [comment]
> Can you reproduce the issue with the Mock Language Server manually? With Run As > Eclipse Application on the test fragment, and running the steps automated in this test?

Nope. I can't. maybe it's because the Linked Editing regions returned by Mock LS are static (not re-calculated on characters typing), but as of now it works correctly with JUnit test we made as well as when I try to test it manually with Mock LS.

**Comment by mickaelistria** [comment]
Merged as https://github.com/eclipse/lsp4e/commit/336301738831ea681027fa5653e4d4a0889d0da2

**Pull request closed without merging**
