### PR TITLE
fix: don't log same BadLocationException excessively

### PR DESCRIPTION
**Pull request by sebthom**
The goal of this PR is to address https://github.com/eclipse/lsp4e/issues/899 , https://github.com/eclipse/lsp4e/issues/536 and https://github.com/eclipse/lsp4e/issues/203 by logging BadLocationExceptions in LSPDiagnosticsToMarkers and SymbolsLabelProvider only when `Platform.getDebugOption("org.eclipse.lsp4e/debug")` is set to true.

### CODE REVIEW

**Comment by rubenporras** [comment]
I prefer to have the exceptions in the log if the error happens. 

Otherwise the user will still miss some feature and will not know why.

Is the error such a problem that we would like to hide it?

**Comment by sebthom** [comment]
I guess the problem is the amount of exceptions being logged repetitively

**Comment by rubenporras** [comment]
What about counting exceptions and only log the first three unless in debug mode?

I think that is a good compromise between informing the user and not bothering him

**Comment by sebthom** [comment]
> What about counting exceptions and only log the first three unless in debug mode?
> 
> I think that is a good compromise between informing the user and not bothering him

@rubenporras ok, please check my update

**Review by rubenporras — APPROVED** [review]
Thanks

**Pull request merged**
