### PR TITLE
Fixed #958 Add ID to menu to allow external contributions

### LINKED ISSUE #958: Add ID to menu to allow external contributions
The plugin `org.eclipse.lsp4e` contributes menus without IDs. This prevent external contributions.

### PR DESCRIPTION
**Pull request by ylussaud**

### CODE REVIEW

**Review by mickaelistria — APPROVED** [review]
Thanks, we'll merge this patch as soon at the CI passes.
Can you please elaborate a bit about the underlying user-story? Is this something that is intended to add support for custom LSP-based operations? I'm asking because I think such menus which are common to most code editors would probably be better defined in the Generic Editor directly. What do you think?

**Comment by ylussaud** [comment]
I made some refactoring commands server side and want to contribute them in Eclipse (client) side. For the moment I made the contribution to my own menu, but it would make more sens to contribute to existing LSP4E menus. And I guess others might be interested as well.

The `Refactorings` menu is contributed by LSP4E and I'm contributing refactoring commands... But for other commands I will have a look at menus contributed by the Generic Editor.

**Comment by mickaelistria** [comment]
I think on longer term, it would be better to have the Source & Refactorings menus contributed by the Generic Editor correctly as any code editor is likely to want those, and LSP4E just feeding them.

**Comment by ylussaud** [comment]
Yes that make sens.

**Comment by mickaelistria** [comment]
If you want to lead this effort and contribute those menus to generic editor, please feel free, that would be very welcome!

**Comment by ylussaud** [comment]
I opened the following [issue](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1785) for the Generic Editor.

BTW the Generic Editor already provides a source menu: [org.eclipse.ui.genericeditor.source.menu](https://github.com/eclipse-platform/eclipse.platform.ui/blob/3f00c8b2d69ac6f06a803c046a61a9a104ba5790/bundles/org.eclipse.ui.genericeditor/plugin.xml#L101C20-L101C60).

**Pull request merged**
