### PR TITLE
New API: Port HighlightReconcilingStrategy

### PR DESCRIPTION
**Pull request by rubenporras**

### CODE REVIEW

**Comment by rubenporras** [comment]
@ahmedneilhussain, does it look good to you?

**Comment by ahmedneilhussain** [comment]
The change looks great to me.

**Comment by ahmedneilhussain** [comment]
Unrelated to this change, is document highlight working correctly at the moment? I wasn't aware it was even implemented as an LSP feature until I dug into this code recently, because I've never seen it working. AIUI, this is the feature that should show e.g. other instances of a variable in scope when you click on one of them (as it does in Java). If I try this using corrosion then I can see the requests firing and the response coming back but never see any highlights.

**Comment by rubenporras** [comment]
It works for me in the latest released LSP4E, but we use our own server, I cannot tell with corrosion.

**Pull request merged**
