### PR TITLE
Show DocumentSymbol.Detail in Outline View

### PR DESCRIPTION
**Pull request by gerdleon**
In this change the SymbolLabelProvider is extended to show the detail string that is part of the DocumentSymbol response.

Addresses  #250.

Signed-off-by: Gerd Grossmannn <gerd.grossmann@avaloq.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
Can you please squash those commits, push force it to your branch, and "undraft" it if you think they're good to be merged (looks good to me).

**Comment by gerdleon** [comment]
Will do.

**Comment by rubenporras** [comment]
Hi @mickaelistria ,

excuse me if it is something I should know, but is it not enough that we use the Squash and merge

image

once the change is ready for review?

Why do we ask to do that manually?

Thanks

**Comment by gerdleon** [comment]
@mickaelistria I am new to GitHub, is the approach of @rubenporras ok with you?

**Comment by mickaelistria** [comment]
Indeed, Squash and Merge could work, but currently build is failing. Rebasing (and squashing locally if possible) will allow the build to process better and then -when it passes- we can merge.

$ git fetch origin master
$ git fetch origin pull/284/head
$ git checkout FETCH_HEAD
$ git rebase --onto origin/master
$ git push --force gardleon HEAD:master

will update these commits and push and updated version that build should be able to process. Then we can merge.

**Comment by rubenporras** [comment]
the build fails because https://download.eclipse.org/mylyn/docs/releases/3.0.42/ has disappeared. We need to fix that first. I will create a PR

**Comment by rubenporras** [comment]
@gerdleon , please rebase on main, them the build should success.

**Comment by rubenporras** [comment]
looks good now and it builds fine, so squashing and merging.

**Pull request merged**
