### PR TITLE
Don't create a reconciler Thread for higlight and linked editing range.

### PR DESCRIPTION
**Pull request by angelozerr**
Don't create a reconciler Thread for higlight and linked editing range.

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
I think it makes sense in LSP4E because it already uses async operations/futures, so the extra thread is useless. This should probably be documented on `NoThreadReconciler` to explain why a different pattern then the usual AbstractReconciler can be used here.

**Comment by angelozerr** [comment]
> I think it makes sense in LSP4E because it already uses async operations/futures, so the extra thread is useless. 

It is indeed useless because all reconcile methods are implemented with empty code.

**Comment by mickaelistria** [comment]
One thing is that a documentListener will cause the requests to be sent on every change, while if we stick to a reconciler, there is IIRC a delay before running the desired work to not invalidate/execute it too often while user is typing. I think we should honor that an only send requests after the usual delay.

**Comment by angelozerr** [comment]
> One thing is that a documentListener will cause the requests to be sent on every change, while if we stick to a reconciler, there is IIRC a delay before running the desired work to not invalidate/execute it too often while user is typing.

Indeed but for higlight and linked editing range LSP4e implement reconcile mthod with empty, so we don't need that and more we don't need for those operations a document listener. I will remove this usnused document listener.

**Comment by mickaelistria** [comment]
As mentioned, I don't think we should go for a reconciler without thread. We should instead use some MonoReconciler, drop the document listener, and make the LS request as part of the reconcilingStrategy.
The 500ms is useful, and reconciler already has a document listeners, we should just embrace those for a better UX.

**Comment by angelozerr** [comment]
> The 500ms is useful, and reconciler already has a document listeners, we should just embrace those for a better UX.

The 500ms is used only when you implemnt reconcile methods. In our case we don't implement it.

**Comment by mickaelistria** [comment]
> The 500ms is used only when you implemnt reconcile methods. In our case we don't implement it.

Exactly, and I think this is an issue. We should instead remove the document listener and implement those methods.

**Comment by angelozerr** [comment]
> Exactly, and I think this is an issue. We should instead remove the document listener and implement those methods.

Higlight reacts on selection changes and linked editing range don't need to react on some reconcile or document change. So we dont need to react on some document change (on reconcile or document change lsitener).

**Comment by mickaelistria** [comment]
Sorry, I was mixing highlights and hyperlinks. So you're entirely right (again!) that both those operations do not require a thread. However, what value does NoThreadReconcilier bring over plain `IReconciler`?

**Comment by angelozerr** [comment]
@mickaelistria I think we should manage with clean mean this topic of Thread with https://github.com/eclipse-platform/eclipse.platform.text/issues/85

**Comment by angelozerr** [comment]
Closed for https://github.com/eclipse/lsp4e/pull/272

**Pull request closed without merging**
