### PR TITLE
Allow progress report messages to be applied for indefinite progress

### PR DESCRIPTION
**Pull request by BoykoAlex**
Partially address #504  - the last part of it.

I can submit the full PR for #504. Essentially the total work for the progress would be hardcoded to 100 and the begin message percentage would be assumed 0 if it is a non null integer.

### CODE REVIEW

**Review by rubenporras — APPROVED** [review]

**Comment by rubenporras** [comment]
Would the rest of #504 be backwards compatible?

**Comment by BoykoAlex** [comment]
> Would the rest of #504 be backwards compatible?

@rubenporras  I wasn't thinking about backward compatibility, but i think it can be made backward compatible...

**Comment by BoykoAlex** [comment]
@rubenporras  Do I need to wait for someone to merge this PR or merge it myself?

**Comment by BoykoAlex** [comment]
@rubenporras i have pushed the commit that I think resolves #504 with backward compatibility support

**Review by rubenporras — APPROVED** [review]

**Comment by rubenporras** [comment]
> > Would the rest of #504 be backwards compatible?
> 
> @rubenporras I wasn't thinking about backward compatibility, but i think it can be made backward compatible...

Thanks, I made the same mistake in the Xtext Language Server as in LSP4E, so not being backward compatible would have broken at least that server

**Pull request merged**
