### PR TITLE
Change default timeout

### PR DESCRIPTION
**Pull request by rubenporras**

### CODE REVIEW

**Review by sebthom — APPROVED** [review]

**Review by sebthom — CHANGES_REQUESTED** [review]
Some test cases are now failing

**Comment by ahmedneilhussain** [comment]
Are the test failures unrelated? They look suspiciously like this area of functionality

**Comment by sebthom** [comment]
I would say:
1. [org.eclipse.lsp4e.test.LanguageServiceAccessorTest.testDontRestartUnrelatedLSForFileFromSameProject](https://ci.eclipse.org/lsp4e/job/lsp4e-github/job/PR-411/1/testReport/junit/org.eclipse.lsp4e.test/LanguageServiceAccessorTest/testDontRestartUnrelatedLSForFileFromSameProject/) => related
1. [org.eclipse.lsp4e.test.LanguageServiceAccessorTest.testLastDocumentDisconnectedTimeoutZero](https://ci.eclipse.org/lsp4e/job/lsp4e-github/job/PR-411/1/testReport/junit/org.eclipse.lsp4e.test/LanguageServiceAccessorTest/testLastDocumentDisconnectedTimeoutZero/) => related
1. [org.eclipse.lsp4e.test.edit.DocumentRevertAndCloseTest.testShutdownLsp](https://ci.eclipse.org/lsp4e/job/lsp4e-github/job/PR-411/1/testReport/junit/org.eclipse.lsp4e.test.edit/DocumentRevertAndCloseTest/testShutdownLsp/) => related
1. [org.eclipse.lsp4e.test.highlight.HighlightTest.testCheckIfOtherAnnotationsRemains](https://ci.eclipse.org/lsp4e/job/lsp4e-github/job/PR-411/1/testReport/junit/org.eclipse.lsp4e.test.highlight/HighlightTest/testCheckIfOtherAnnotationsRemains/) => NOT related

**Comment by mickaelistria** [comment]
I don't have an objection, and I support the idea.
But some tests indeed need to be updated. The change can simply be to set timeout to 0 for the test language servers to restore the legacy behavior expected by the tests.

**Comment by rubenporras** [comment]
right, some tests needs fixing, I will not be able to do it today or early next week, but I can take a look later. If someone can fix it before, he would be welcome!

**Review by sebthom — APPROVED** [review]

**Pull request merged**
