### PR TITLE
initial draft for inline value text support

### PR DESCRIPTION
**Pull request by bastiandoetsch**
- supports getting inline values via `textdocument/inlineValue`
- refreshes via `workspace/inlineValue/refresh`
- registers the client capability
- implements a code mining provider for inline values

### CODE REVIEW

**Comment by bastiandoetsch** [comment]
Parsing of InlineValue[] array from LS fails right now. The array contains `InlineValueText` objects.

Input for parsing:
```{"jsonrpc":"2.0","id":"2","result":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":2147483647}},"text":"IaC Test InlineValue"}]}
```
```
Jun 21, 2023 12:53:34 PM org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: Ambiguous Either type: token BEGIN_OBJECT matches both alternatives.
com.google.gson.JsonParseException: Ambiguous Either type: token BEGIN_OBJECT matches both alternatives.
	at org.eclipse.lsp4j.jsonrpc.json.adapters.EitherTypeAdapter.create(EitherTypeAdapter.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.EitherTypeAdapter.read(EitherTypeAdapter.java:177)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.EitherTypeAdapter.read(EitherTypeAdapter.java:40)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapter.read(CollectionTypeAdapter.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapter.read(CollectionTypeAdapter.java:40)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1186)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.fromJson(MessageTypeAdapter.java:345)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.parseResult(MessageTypeAdapter.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:125)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:57)
	at com.google.gson.Gson.fromJson(Gson.java:1227)
	at com.google.gson.Gson.fromJson(Gson.java:1186)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:119)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:114)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by bastiandoetsch** [comment]
@angelozerr thought this may perhaps interest you.

**Comment by bastiandoetsch** [comment]
Looks like the bug in LSP4j is gonna be fixed soon.

**Comment by mickaelistria** [comment]
What's the status here?

**Comment by bastiandoetsch** [comment]
I'm waiting for the next LSP4j release to be integrated into LSP4e, then I rebase against main and promote the PR from draft :)

**Comment by bastiandoetsch** [comment]
See https://github.com/eclipse-lsp4j/lsp4j/issues/753

**Comment by mickaelistria** [comment]
OK, feel free to add to your PR a commit for LSP4E to use latest (2-days old IIRC) LSP4J release.

**Comment by bastiandoetsch** [comment]
Yeah, just checked. It's tagged with the 0.22.0 milestone.

**Comment by bastiandoetsch** [comment]
Still waiting for LSP4j - I've asked when the 0.22.0 release is gonna happen.

**Comment by bastiandoetsch** [comment]
Exciting times - as 0.22.0 was released last night, this can be picked up again.

**Comment by jonahgraham** [comment]
> @bastiandoetsch Cool, feel free to 1st submit a PR moving LSP4E to use LSP4J 0.22, so this can then be worked more efficiently.

@bastiandoetsch the move to LSP4J 0.22 has been done now by @akurtakov in https://github.com/eclipse/lsp4e/pull/919

**Comment by bastiandoetsch** [comment]
Looking into it once more now :)

**Comment by mickaelistria** [comment]
The initial target branch `master` was deleted and replaced by `main`, so this PR got closed automatically. If this is still relevant, please re-create this PR targetting the `main` branch.

**Pull request closed without merging**
