### PR TITLE
refact: Use `var` keyword and `List.of` and `Set.of` where applicable

### PR DESCRIPTION
**Pull request by sebthom**
*Please don't squash this commit when merging for better transparency of the changes.*

This PR applies various refactorings to the code base, mainly:
1. it makes use of the `var` keyword for local variable assignment where the actual type is immediately recognizable through an implicit cast or a constructor call on the right side of the assignement
2. Replaces usage of `Collections.singletonList` and `Arrays.asList` (if beneficial) with Java 9's `List.of`
3. Replaces usage of `Collections.sort` in places where an unsafe assumption was made that the input list will always be mutable.

### CODE REVIEW

**Review by rubenporras — APPROVED** [review]

**Comment by rubenporras** [comment]
So after Jenkins can validate the PR, we should use "Rebase and Merge"?

**Comment by sebthom** [comment]
> So after Jenkins can validate the PR, we should use "Rebase and Merge"?

yes please. I usually only use squash when the PR contains unpolished commit messages or multiple commits trying to address the exact same issue.

**Comment by sebthom** [comment]
Jenkins CI is down...

**Comment by mickaelistria** [comment]
Infra failures already reported at https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4914

**Review by rubenporras — APPROVED** [review]

**Pull request merged**
