### PR TITLE
Fix disappearing sort button in outline view (fix #1091)

### LINKED ISSUE #1091: Sort toolbar button disappears in outline view if an LSP editor is activated
The outline view provides a sort button. It is available as long as the outline view is active. As soon as instead an LSP editor becomes active, the button disappears, although the LSP editor provides the outline page that is still visible.

Examples:

Outline view is active, sort button is visible in the toolbar:
image

LSP editor is active, the sort button disappeared:
image

I found this issue while working on PR #1075.

### PR DESCRIPTION
**Pull request by travkin79**
This PR should be merged before merging PR #1075.

### CODE REVIEW

**Comment by rubenporras** [comment]
Could you explain why the fix works in the commit (and PR) message? I am not very skilled on this area of Eclipse, and just from looking at the PR, I cannot tell why it was broken before and why it is fixed now.

**Comment by travkin79** [comment]
Yes. Previously, the sort button was only active if the active part was the outline view. As soon as an editor became active, the `visibleWhen` expression became `false` and the sort button disappeared. The check was done by the expression definition named `activePartHasCNFOutlinePage`.

I added a new expression definition named `activeEditorHasCNFOutlinePage`. I changed the `visibleWhen` expression to only check if the (last) active editor (that does not necessarily has to be in focus) has an outline page of type `CNFOutlinePage`. The remaining checks using the expression `activePartHasCNFOutlinePage` are left unchanged.

**Comment by rubenporras** [comment]
Thanks for the explanation. I understand now. Can you amend the commit message with the explanation? then I would be happy to merge.

**Review by rubenporras — APPROVED** [review]
Thanks

**Comment by travkin79** [comment]
Thank you, @rubenporras . 😄

**Pull request merged**
