### PR TITLE
Rename head branch to main and update documentation links

### PR DESCRIPTION
**Pull request by sebthom**
This PR changes all references from "master" to "main". Besides the merge of this PR renaming the branch to `main` and setting it as default branch is required.

### CODE REVIEW

**Comment by mickaelistria** [comment]
I'm OK with that. @rubenporras what do you think?

**Comment by rubenporras** [comment]
I am also OK with the change. @sebthom, would you do the rename of the branch, etc. yourself after merging?

**Comment by sebthom** [comment]
@rubenporras I don't think I have permission to change the default branch.

**Comment by rubenporras** [comment]
I also do not know if I have the rights. @mickaelistria , do you know if you have them?

**Comment by mickaelistria** [comment]
No, I don't. but we can proceed anyway, and just hope GitHub makes the right choice. If it doesn't, then we'll have to open an helpdesk ticket. The EF staff will encourage use to have our own `eclipse-lsp4e` GitHub orgs which would give committers and leads more power.

**Pull request merged**
