### PR TITLE
Allow extended marker attributes

### PR DESCRIPTION
**Pull request by rubenporras**

### CODE REVIEW

**Comment by mickaelistria** [comment]
Can you please rebase on top of master? Commits were squashed.

**Comment by rubenporras** [comment]
> Can you please rebase on top of master? Commits were squashed.

Yes, I will do that if we want to merge this one

**Comment by rubenporras** [comment]
This version I like less than PR-88, as it requires to calculate the markers derived from the resource for each diagnostic at it is only slightly simpler.
Just let me know which one you would like to merge and then I rebase & squash it.

**Comment by rubenporras** [comment]
Let us close this PR and follow on PR-88

**Pull request closed without merging**
