### PR TITLE
Linked editing doesn't exit on whitespaces and other non-word chars #94

### PR DESCRIPTION
**Pull request by vrubezhny**
LinkedRditingRange's wordPattern value is used to control the linked editing. The value of the wordPattern is to be provided
by the active LS, otherwize a common Unicode Indentifier  pattern is used to validate the input.

Change-Id: I6291f7136fbdb8f4ee3f067d8b17c74400067676
Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
This looks good to me. Shall we merge now?

**Comment by vrubezhny** [comment]
It looks like there's a difference in how a wordPattern is processed in VSCode and in this fix. See https://github.com/eclipse/lemminx/pull/1188#discussion_r838759117

Probably we need to make it  to be inline with VCSode way.

**Comment by mickaelistria** [comment]
Thanks!

**Comment by mickaelistria** [comment]
There is one test failing with this PR now.

**Comment by vrubezhny** [comment]
> There is one test failing with this PR now.

I don't think that the test failure was anyhow related to the change. The only problem I found in Jenkins logs is a `ConcurrentModificationException` occurrence, for which I have added a fix to this PR. 

Currently the PR is build with success.

**Pull request merged**
