### PR TITLE
DSPProcess::getExitValue should only raise an exception if the process is still alive

### PR DESCRIPTION
**Pull request by FlorianKroiss**
Fix small logic error when checking if thread is still alive

### CODE REVIEW

**Comment by FlorianKroiss** [comment]
I haven't setup ECA yet, but maybe someone can apply this simple fix directly and close this PR?

**Comment by mickaelistria** [comment]
We're not allowed to merge any code that was authored by anyone who didn't sign the ECA. If you're OK getting your code merged, then better just sign the ECA directly.

**Comment by FlorianKroiss** [comment]
@mickaelistria sorry for the delay, but the legal stuff should be alright now.

**Comment by mickaelistria** [comment]
can you please update the version in MANIFEST.MF for the modified bundle and its pom.xml by +0.0.1 by the way so CI build is more likely to succeed?

**Comment by mickaelistria** [comment]
Thank you!

**Pull request merged**
