### PR TITLE
Completion "hangs" with no response #743

### PR DESCRIPTION
**Pull request by vrubezhny**
Getting rid of infinite waiting in LSContentAssistProcessor

Issue: #743

### CODE REVIEW

**Comment by vrubezhny** [comment]
IMHO, the failing JUnit test cases are not related to the fix - the PR is built 3 times - every time the test failures were different.

**Comment by vrubezhny** [comment]
Unfortunately, the stack trace doesn't allow to determine which exact test generated the TimeoutException:
```
org.eclipse.lsp4e.test.edit.LSPEclipseUtilsTest.testResourceOperations -- Time elapsed: 0.116 s <<< FAILURE!
java.lang.AssertionError: Some errors were logged expected:<[]> but was:<[Status ERROR: org.eclipse.lsp4e code=0 TimeoutException java.util.concurrent.TimeoutException]>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.eclipse.lsp4e.test.NoErrorLoggedRule.finished(NoErrorLoggedRule.java:61)

```
and
```
SEVERE: Status ERROR: org.eclipse.lsp4e code=0 TimeoutException java.util.concurrent.TimeoutException
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$10(LanguageServerWrapper.java:458)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
But as we don't see any tests failed - it looks like actually the `LSPEclipseUtilsTest.testResourceOperations` test cases is succeeded - and timeout exception actually didn't hurt the execution, but `NoErrorLoggedRule` rule has marked it as "failed".
I don't know if it was actually a real "resource operation problem" or it's just that it took too much time for some reason - it still worth investigating, but timeouts may happen and logged and in most real cases are not because of any failure - we just need to be prepared and process them accordingly.

**Comment by sebthom** [comment]
@vrubezhny I created PR #749 which should improve the build stability.

**Comment by angelozerr** [comment]
Please see an another proposal to fix completion hang https://github.com/eclipse/lsp4e/pull/750

**Comment by rubenporras** [comment]
@vrubezhny, I think the approach proposed by @angelozerr is preferable, as it does not need a timeout that might discard useful answers just because they are a bit too late, and I also expect it would be more responsive as it is able to cancel futures that are no longer needed. What do you think?

**Comment by mickaelistria** [comment]
> I already addressed some of them but I feel it is getting worse. maybe something in the jenkins infrastructure changed

I have not followed recent developments as I was on holiday, but often when this has happened, it can be caused by an actual performance regression in LSP4E itself more than an infra issue.

**Comment by mickaelistria** [comment]
Damn, I hit "merge" by mistake.
For completion processors, operations can be very long yet very valuable. For some cases where completion would be a very deep analyzer, it could be OK to wait 15 seconds for the output of a completion request (imagine this one generates a whole software...).
What we want here is indeed @rubenporras mentioned and @angelozerr suggests: support for proper cancellation.
So I'm reverting it.

**Comment by rubenporras** [comment]
I am not sure if in addition to @angelozerr suggestion, we still need this PR or some improved version, but I am happy that we are cautious here. The cancellation support could be merged and it should improve the situation, what do you think, @mickaelistria ?

**Pull request merged**
