### PR TITLE
LanguageServerWrapper: Don't set rootURI if initialProject and initialPath are null or invalid

### PR DESCRIPTION
**Pull request by sebthom**
...in case LanguageServerWrapper initialProject and initialPath are null or
point non-existing location

### CODE REVIEW

**Comment by mickaelistria** [comment]
I'm not sure it's a good choice. In many cases, the projects that are visible in the workspace are not children of the workspace location on filesystem. I'm thinking maybe it would be possible to pass no root in such case?

**Comment by sebthom** [comment]
> I'm thinking maybe it would be possible to pass no root in such case?

@mickaelistria This makes even more sense to me. I pushed an update.

**Review by rubenporras — COMMENTED** [review]
The code makes sense to me. Did you checked if the two test failures are related to the commit?

**Comment by sebthom** [comment]
> Did you checked if the two test failures are related to the commit?

Good catch! Fixed it.

**Comment by rubenporras** [comment]
@sebthom , looks good to me know, but I would leave @mickaelistria the final review.

**Comment by mickaelistria** [comment]
I didn't try it yet but the idea and code seems good. Let's merge and release to snapshots to give time to get feedback.

**Pull request merged**
